experimenter: 'jyr'
savedir: /home/julianarhee/data/videos
codec: 'libx264' # DIVX has compression artifacts. set to 0 for uncompressed
# the reason that we have to set these here is that all realsense cameras should be 
# the same fps and h,w for synchronization + calibration purpose
# look in realsense_presets.yaml for good examples
basler_options:
  Width: 1024
  Height: 768
  Framerate: 120.0
  emitter_enabled: 1 # must be 1 or 0, not true / false
  Exposure: 8000.0 #68295.0
  Gain: 1
  Uncompressed: False
cams:
  sideview: 
    type: Basler
    master: False
    serial: 24516213
    # set options to none to use default
    options:
      # note: modify these at your own risk! don't change the order!
      # many have dependencies that are hard to figure out, so the order matters.
      # for example, exposureauto must be set to off before exposuretime can be changed. 
      AcquisitionMode: 'Continuous' # can capture one frame or multiple frames as well
      ExposureAuto: 'Off' # manually set exposure
      ExposureMode: 'Timed'
      ExposureTime: 8000.0 #68290.0 #1000.0 # in microseconds, so 1000 = 1ms
      # this downsamples image in half, enabling faster framerates
      # it's not possible to change binninghorizontal, but it is automatically changed by changing
      # binningvertical
      BinningVerticalMode: 'Average'
      BinningHorizontalMode: 'Average'
      BinningVertical: 3
      BinningHorizontal: 3
      Height: 512 #768 # max 1024 if binning=1, else 512
      Width: 680 #1024 # max 1280 if binning=1, else 640
      OffsetX: 0 # left value of roi
      OffsetY: 0 # top value of roi
      CenterX: True
      CenterY: True
      PixelFormat: Mono8
      AcquisitionFrameRateEnable: True
      AcquisitionFrameRate: 120.0
      GainAuto: 'Off'
      Gain: 0.0
      Gamma: 1.0 #1.0
      #SharpnessAuto: 'Off'
    strobe:
      line: 4 #3
      duration: 0.0
      trigger_selector: 'FrameStart'

